#!/usr/bin/env bash
#Comment
while IFS=: read -r username pswd uid gid info home shell; do
    echo The user "$username" is part of the "$gid" gang, lives in "$home" and 
and rides "$shell". "$uid's" place is protected by the passcode "$pswd",
more info about the user here: "$info"

done < /etc/passwd

