#!/usr/bin/env bash
#Comment
PIDFILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

case "$1" in
    start)
        $PROCESS &
        echo $! > $PIDFILE
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        # Stop
        if [ -f "$PIDFILE" ]; then
            kill "$(cat $PIDFILE)" 2>/dev/null
            rm -f "$PIDFILE"
        fi
        # Start
        $PROCESS &
        echo $! > $PIDFILE
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
